### ISSUE TITLE
Predefined Azure Client 

### ISSUE THREAD

**Issue by Eradparvar** [teranetsrl/oauth2_client#153]
Thank you for a great package.

I would like to create a pull request to add Microsft to the list of predefined clients. Can you offer any guidance and steps to accomplish this?

Authorization code grant flow
https://learn.microsoft.com/en-us/graph/auth-v2-user

Client credentials grant flow
https://learn.microsoft.com/en-us/graph/auth-v2-service 

Thank you

**Comment by okrad** [comment]
Hi @Eradparvar, 
you could create a new AzureOAuth2Client class  by following the instructions in the [README](https://github.com/teranetsrl/oauth2_client#implementing-your-own-client), or you could start off by copying one of the  existing clients (github, reddit, ...).

Let me know if you have any problems figuring out how to implement possible peculiarities of the Azure client.

Eventually I'm thinking of moving all the clients into their own separate folder, but since it would be a breaking change I'm hanging on till the next major release.

**Comment by Eradparvar** [comment]
Thanks for your response, I added it to my list of things to do. I hope to send updates soon.

**Comment by Eradparvar** [comment]
done :) Please let me know your thoughts and if you want me to change anything.

Side note the flutter_secure_storage version 7.0.1 cant store tokens larger than 2561 bytes on windows. There is a fix in flutter_secure_storage version 8.0.0  There are breaking changes from upgrading the flutter_secure_storage from 7.0.1 to version 8.0.0. What is the best way to update the code?

reference:
https://github.com/mogol/flutter_secure_storage/pull/505

**Comment by okrad** [comment]
Thank you @Eradparvar!
