### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by manjotsidhu** [teranetsrl/oauth2_client#66]
This is a request to add support for [null safety](https://dart.dev/null-safety) .
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See this [blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide)  for details about enabling null safety.

**Comment by okrad** [comment]
Hi @manjotsidhu, I'm already working on it!

**Comment by okrad** [comment]
Hi @manjotsidhu, null safety support has landed with the new release (2.0.0-nullsafety)!
I couldn't migrate all of the dependencies, since flutter_web_auth still doesn't implement null safety. This shouldn't be too much of a hassle, anyway as soon as it gets migrated I will update oauth2_client too.

**Comment by manjotsidhu** [comment]
> Hi @manjotsidhu, null safety support has landed with the new release (2.0.0-nullsafety)!
> I couldn't migrate all of the dependencies, since flutter_web_auth still doesn't implement null safety. This shouldn't be too much of a hassle, anyway as soon as it gets migrated I will update oauth2_client too.

Thank you!
