### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by oldbig** [teranetsrl/oauth2_client#7]
How to logout? It seems no that method in OAuth2Helper.

**Comment by okrad** [comment]
Hi @oldbig, the OAuth standard doesn't provide a proper "logout" mechanism since it's not an authentication framework (but rather an authorization framework). It however defines a "Token Revocation" flow which should be used by clients to tell the server that the Access Token or the Refresh Token should be invalidated, so that they cannot be used anymore.

If this is what you need, it's implementation is currently in the work, and should be available in the next release.

**Comment by oldbig** [comment]
Hi @okrad  I am clear.
Thank you very much !

**Comment by TheFedex87** [comment]
Hi, I'm trying to use the disconnect method of helper, and also revokeToken method, but they seems doesn't work. Token is deleted locally, but if I try to use that token it is still valid

**Comment by okrad** [comment]
Hi @TheFedex87, you are right, I obviously misunderstood the specs when I first read the revocation flow...
If you don't mind creating a pull request I will surely consider merging it.

**Comment by TheFedex87** [comment]
@okrad pull request done! ;)

**Comment by okrad** [comment]
Thank you, I just merged it... 
I made some small modifications converting the clientid parameter as an optional one, and adding an optional client secret.
