### ISSUE TITLE
TokenStorage not working correctly

### ISSUE THREAD

**Issue by jimad7** [teranetsrl/oauth2_client#8]
Hi

I've a problem with TokenStorage. I'm using OAuth2Helper.AUTHORIZATION_CODE with scope parameters ['api', 'openid', 'profile']. After login i'm trying to do a get. But the token is null from TokenStorage and i'm prompt to login again. There seems to be a problem with the scopeKey not being correctly defined when writing and getting tokens from TokenStorage.

**Comment by okrad** [comment]
Hi, what happens when you authenticate for the second time? Does the token get created? 
Would you mind providing a code sample?

**Comment by ResoDev** [comment]
Hello! Same here.
I'm using the GitHub API and this issue occurs because the scopes we provide to the `OAuthClient` are list of strings: `['repo', 'notifications']`. The scopes which are returned from GitHub are, however, not a list of strings but instead one long string `'repo;notifications'`.
It seems that at least for the GitHub API, the solution would be to split the response string at `;`.

**Comment by jimad7** [comment]
Trying to explain a bit more without a code sample.

I'm using scopes ['api', 'openid', 'profile'].

For me the getToken method sets scopeKey to 'api__openid__profile'.

The insertToken method, scopeKey is set to 'openid profile api'.

The tokens map is set to:
 {
openid profile api: {http_status_code: 200, access_token:..}
}

**Comment by jimad7** [comment]
I saw that I've had wrong order in my scope list.

The scopes that returned token contains is [openid profile api]. A different order than my configuration. But even if a change my configuration to exactly that order to:  ['openid', 'profile', 'api'] it still doesn't work.

On this line scopeKey is openid__profile__api.
if (tokens.containsKey(scopeKey))  

But the tokens key is : 
{openid profile api: {...

Hope that explains it a bit more.

**Comment by okrad** [comment]
Hi @jimad7 and @ResoDev, thank you for taking the time of looking into the issue!
You are both right: the scopes that are sent from GitHub are a comma-separated list (instead of space-separated as by the rfc)... We need to handle this exception. 
Furthermore the scope key generation method must take into account the order of the scopes.

I'm already working on these issues, fixes should be released very soon.

**Comment by okrad** [comment]
Just published version 1.2.3... Does it solve your issues?

**Comment by ResoDev** [comment]
It does for me. Thank you!

**Comment by jimad7** [comment]
Hi, it does for me too. Thank you!

**Comment by okrad** [comment]
Fine!
